### ISSUE TITLE
ansito returns ${color} for all colors it got from taskwarrior

### ISSUE THREAD

**Issue by sim590** [pawamoy/ansito#5]
**Describe the bug**

When running the following command:
```
task limit:10 rc.defaultwidth:100 rc._forcecolor:on rc.verbose:affected,blank doing
```
the following characters are produced:
```
[4mID[0m [4mÉtiquettes   [0m [4mDescription      [0m
[38;5;15m[48;5;39m49[0m[38;5;15m[48;5;39m [0m[38;5;15m[48;5;39machat bientôt[0m[38;5;15m[48;5;39m [0m[38;5;15m[48;5;39mChaise d'ordi    [0m

1 task
```
and it displays like this on the terminal:
![task-couleur-terminal](https://user-images.githubusercontent.com/4147254/123533920-42b6d580-d6e7-11eb-8819-78e1e288252d.png)
However, when running the following command:
```
task limit:10 rc.defaultwidth:100 rc._forcecolor:on rc.verbose:affected,blank doing | ansito -
```
the following output is produced:
```
ID${color} Étiquettes   ${color} Description      ${color}
49${color} ${color}achat bientôt${color} ${color}Chaise d'ordi    ${color}

1 task
```
Notice that no sensible colors are produced in the conky format.

**Expected behavior**
Corresponding valid color codes should be produced in order for Conky to display them.

**System:**
- `ansito` version: 0.1.0
- Python version: Python 3.9.5
- OS: Archlinux

**Additional context**

Running the following:
```
task limit:10 rc.defaultwidth:100 rc._forcecolor:on rc.verbose:affected,blank doing | conky-bg-space-to-fg.sh | ansito -
```
where `conky-bg-space-to-fg.sh` is as found [here][conky-bg], actually gives a more sensible output:
```
ID${color} Étiquettes   ${color} Description      ${color}
49${color}${color #00afff}█${color}${color #00afff}achat█bientôt${color}${color #00afff}█${color}${color #00afff}Chaise█d'ordi    ${color}

1 task
```
However, extra colored space are added, as depicted in the following screencapture, which I don't want.
![task-espace-en-plus](https://user-images.githubusercontent.com/4147254/123534166-1d2acb80-d6e9-11eb-8089-51e95adaef44.png)

[conky-bg]: https://gist.github.com/pawamoy/6fe205525fc653474e88bad582ef90fa#file-conky-bg-space-to-fg-sh

**Comment by sim590** [comment]
I have just thought about it and may be there's nothing wrong after all since all foreground colours are white in my example and `ansito` is just writing foreground colours...

As you said here:

https://www.reddit.com/r/Conkyporn/comments/dvgm6r/text_foregroundbackground_color/f7ezn16/?utm_source=reddit&utm_medium=web2x&context=3

There is no background colour functionality apparently so it explains why I was looking for colours in the output, but was not seeing any.

**Comment by pawamoy** [comment]
Hello, thank you for the very detailed bug report, and sorry you had trouble using ansito!

Indeed, there's no background color functionality in Conky (just checked again on the web to be sure), so ansito does not know what to do with the ANSI background color codes.

I should probably mention this in the README!

Thanks again, have a good day :slightly_smiling_face:
